---
image: docker:latest
services:
  - docker:dind
before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

# Build based on Tags
docker-deploy:
  stage: build
  script:
    - |
      export pi_version=${CI_COMMIT_TAG%_*}
      echo "PrivacyIdea Version: $pi_version"
    - >
      docker build
      --pull
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --build-arg BUILD_VERSION="$rundeck_version"
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --tag $CI_REGISTRY_IMAGE:$pi_version
      .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE:$pi_version"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\_\d+$/'
      exists:
        - Dockerfile
